export const SIDEBAR_ACTION = {
  ProcessToView: {
    EXPAND_SIDEBAR_STATE: 'EXPAND_SIDEBAR_STATE'
  },
  ViewToProcess: {
    TOGGLE_EXPAND_SIDEBAR: 'TOGGLE_EXPAND_SIDEBAR'
  }
};

export const TITLE_BAR_ACTION = {
  CLOSE_FROM_CUSTOM_TITLE_BAR: 'CLOSE_FROM_CUSTOM_TITLE_BAR',
  HIDE_FROM_CUSTOM_TITLE_BAR: 'HIDE_FROM_CUSTOM_TITLE_BAR',
  TOGGLE_SIZE_FROM_CUSTOM_TITLE_BAR: 'TOGGLE_SIZE_FROM_CUSTOM_TITLE_BAR'
};

export const MUSIC_ACTION = {
  ProcessToView: {
    MUSIC_FOLDER_SELECT: 'MUSIC_FOLDER_SELECT',
    FIRE_DIR_LIST: 'FIRE_DIR_LIST',
    ADD_DIR: 'ADD_DIR',
  },
  ViewToProcess: {
    SELECT_DIR: 'SELECT_DIR',
    ADD_DIR: 'ADD_DIR',
    REMOVE_DIR: 'REMOVE_DIR'
  }
};

export const APP_ACTION = {
  ProcessToView: {
    PASS_DATA_TO_VIEW: 'PASS_DATA_TO_VIEW'
  },
  ViewToProcess: {
    APP_INIT: 'APP_INIT'
  }
};


